
CREATE TABLE SCHEDULE (
    ID CHAR(10) PRIMARY KEY,
    DAYID INT NOT NULL,
    PERIODID INT NOT NULL,
    SUBCODE CHAR(10) NOT NULL,
    SECTION CHAR(5) NOT NULL,
    FINI CHAR(5) NOT NULL
);

INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('H2', 0, 2, 'BSC402', 'H', 'SKM');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('H8', 1, 2, 'PCCCS403', 'H', 'VP');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('H3', 0, 3, 'BSC402', 'H', 'SKM');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('H6', 1, 0, 'BSC491', 'H', 'ANC');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('H7', 1, 1, 'BSC491', 'H', 'ANC');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('H9', 1, 3, 'PCCCS402', 'H', 'DC');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('H10', 1, 4, 'PLT401', 'H', 'AT');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('H11', 1, 5, 'PLT401', 'H', 'AT');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('H20', 3, 2, 'PCCCS401', 'H', 'AT');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('H13', 2, 1, 'PLT401', 'H', 'TM');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('H14', 2, 2, 'PLT401', 'H', 'TM');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('H15', 2, 3, 'HSMC402', 'H', 'SBG');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('H16', 2, 4, 'PCCCS403', 'H', 'VP');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('H17', 2, 5, 'PCCCS403', 'H', 'VP');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('H18', 3, 0, 'PCCCS491', 'H', 'SLC');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('H19', 3, 1, 'PCCCS491', 'H', 'SLC');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('H21', 3, 3, 'BSC402', 'H', 'SKM');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('H22', 3, 4, 'PCCCS493', 'H', 'VP');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('H23', 3, 5, 'PCCCS493', 'H', 'VP');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('H24', 4, 0, 'PCCCS401', 'H', 'SLC');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('H25', 4, 1, 'HSMC402', 'H', 'DKD');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('H26', 4, 2, 'PCCCS401', 'H', 'SLC');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('H27', 4, 3, 'HSMC402', 'H', 'SBG');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('H28', 4, 4, 'PCCCS402', 'H', 'DC');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('H29', 4, 5, 'PCCCS402', 'H', 'DC');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('G1', 0, 1, 'BSC401', 'G', 'SR');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('G2', 0, 2, 'BSC402', 'G', 'SKM');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('G3', 0, 3, 'BSC402', 'G', 'SKM');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('G4', 0, 4, 'PLT401', 'G', 'AT');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('G5', 0, 5, 'PLT401', 'G', 'AT');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('G8', 1, 2, 'PCCCS403', 'G', 'VP');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('G9', 1, 3, 'PCCCS402', 'G', 'DC');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('G10', 1, 4, 'BSC491', 'G', 'ANC');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('G11', 1, 5, 'BSC491', 'G', 'ANC');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('G13', 2, 1, 'PLT401', 'G', 'TM');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('G14', 2, 2, 'PLT401', 'G', 'TM');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('G15', 2, 3, 'HSMC402', 'G', 'SBG');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('G17', 2, 5, 'PCCCS403', 'G', 'VP');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('G16', 2, 4, 'PCCCS403', 'G', 'VP');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('G18', 3, 0, 'PCCCS491', 'G', 'SLC');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('G19', 3, 1, 'PCCCS491', 'G', 'SLC');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('G20', 3, 2, 'PCCCS401', 'G', 'AT');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('G21', 3, 3, 'BSC402', 'G', 'SKM');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('G22', 3, 4, 'PCCCS493', 'G', 'VP');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('G23', 3, 5, 'PCCCS493', 'G', 'VP');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('G24', 4, 0, 'PCCCS401', 'G', 'SLC');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('G25', 4, 1, 'HSMC402', 'G', 'APC');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('G26', 4, 2, 'PCCCS401', 'G', 'SLC');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('G27', 4, 3, 'HSMC402', 'G', 'DKD');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('G28', 4, 4, 'PCCCS402', 'G', 'DC');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('G29', 4, 5, 'PCCCS402', 'G', 'DC');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('H4', 0, 4, 'PCCCS492', 'H', 'KBH');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('H5', 0, 5, 'PCCCS492', 'H', 'KBH');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('G6', 1, 0, 'PCCCS492', 'G', 'KBH');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('G7', 1, 1, 'PCCCS492', 'G', 'KBH');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('C0', 0, 0, 'PCCCS492', 'C', 'KBH');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('C1', 0, 1, 'PCCCS492', 'C', 'KBH');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('C2', 0, 2, 'PCCCS403', 'C', 'VP');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('C3', 0, 3, 'PCCCS403', 'C', 'VP');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('C4', 0, 4, 'PCCCS491', 'C', 'SLC');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('C5', 0, 5, 'PCCCS491', 'C', 'SLC');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('C6', 1, 0, 'BSC401', 'C', 'SR');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('C7', 1, 1, 'BSC401', 'C', 'SR');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('C8', 1, 2, 'PCCCS403', 'C', 'VP');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('C9', 1, 3, 'BSC402', 'C', 'SKM');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('C10', 1, 4, 'BSC491', 'C', 'ANC');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('C11', 1, 5, 'BSC491', 'C', 'ANC');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('C12', 2, 0, 'PLT401', 'C', 'TM');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('C13', 2, 1, 'PLT401', 'C', 'TM');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('C14', 2, 2, 'PLT401', 'C', 'TM');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('C15', 2, 3, 'HSMC402', 'C', 'SBG');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('C16', 2, 4, 'PCCCS402', 'C', 'DC');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('C18', 3, 0, 'PCCCS493', 'C', 'VP');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('C19', 3, 1, 'PCCCS493', 'C', 'VP');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('C20', 3, 2, 'PCCCS401', 'C', 'SLC');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('C21', 3, 3, 'PCCCS401', 'C', 'AT');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('C22', 3, 4, 'PCCCS402', 'C', 'DC');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('C23', 3, 5, 'PCCCS402', 'C', 'DC');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('C17', 2, 5, 'BSC402', 'C', 'SKM');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('C24', 4, 0, 'PCCCS401', 'C', 'SLC');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('C25', 4, 1, 'HSMC402', 'C', 'DKD');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('C26', 4, 2, 'BSC402', 'C', 'SKM');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('C27', 4, 3, 'HSMC402', 'C', 'SBG');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('C28', 4, 4, 'PLT401', 'C', 'AT');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('C29', 4, 5, 'PLT401', 'C', 'AT');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('H1', 0, 1, 'CSE3133', 'H', 'DJ');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('H12', 2, 0, 'CSE3002', 'H', 'SCB');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('G12', 2, 0, 'CSE3002', 'G', 'SCB');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('G0', 0, 0, 'CSE3101', 'G', 'SCB');
INSERT INTO SCHEDULE (ID, DAYID, PERIODID, SUBCODE, SECTION, FINI) VALUES ('H0', 0, 0, 'CSE3101', 'H', 'SCB');

ALTER TABLE SCHEDULE
ADD CONSTRAINT unique_teacher_period
UNIQUE (DAYID, PERIODID, FINI);
